// *** Generated by OFS compiler *** 
 import { Stream } from "../src/utils/stream.mjs"
const printIt = it => console.log

(it)
const parity_map_50 = Stream.iterate( 0, n => n + 1).filter(n => (n != 0) ? "odd" : "even").cut( 50)

parity_map_50.map(printIt)
